baseURL = "https://heilpraxis-traeuble.github.io/"
languageCode = "de-de"
title = "Naturheilpraxis Träuble"
theme = "alpha-church"

rssLimit = 5
paginate = 4

enableEmoji = true

googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Übersicht"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Über mich"
    url = "/about"
    weight = 2

# Paramaters for the whole site
[params]
  title = "Naturheilpraxis Träuble"
  subtitle = ""
  author = "Ursula Träuble"
  keywords = ["theme", "hugo"]
  languageCode = "de"
  instant_page = true

  customCSS = ["custom.css"]

  [params.favicon]
    sml = "/example16.png"
    med = "/example32.png"
    #lge = "example96.png"

  [params.banner]
    image = "img/header_blatt.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (otherwise users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree form_id.
    #
    #If you use php, you need to host this site on a Server capable of running php.
    # Please edit the /static/contact_mail.php file from the exampleSite.
    service = "netlify" #or "formspree" or "php"
    confirm_page = "/contact_thanks" #only used by netlify
    # formspree_formid="" #only used by formspree


    [params.footer]
      copyright = ["Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]
